[package]
name = "nickit_backend"
version = "0.0.1"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
ldap3 = "0.4.4"
serde = "1.0.11"
serde_derive = "1.0.11"
toml = "0.4.2"
